

FROM python:3.10-slim

WORKDIR /app

RUN apt-get update --yes && \
    apt-get install --yes --no-install-recommends \
    gcc \
    python3-dev && \
    # Clean up apt lists to keep the image size small
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
# Copy the downloaded model from the previous stage

# Copy requirements file and install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy your application code and the ONNX model directory
COPY main.py ./
COPY streamlit_app.py ./
COPY onnx_model/ ./onnx_model/

# Expose the port FastAPI runs on
EXPOSE 8000 8001

# Command to run the entrypoint script
COPY entrypoint.sh ./
RUN chmod +x entrypoint.sh
CMD ["./entrypoint.sh"]
